"use client";import {useEffect,useState} from "react";
const gifts=["Neckband","Earbuds","2 साल की Mobile Warranty","₹999 Next Purchase Coupon","Tempered Glass","Mobile Holder","Juicer Mixer","Bluetooth Speaker","Iron Press","Cycle 🚲"];
type LinkRow={id:number;customerName:string;mobile:string;prize:string;status:string;createdAt:string;usedAt:string|null;token:string};
export default function Admin(){const [pin,setPin]=useState(""),[ok,setOk]=useState(false),[name,setName]=useState(""),[mobile,setMobile]=useState(""),[prize,setPrize]=useState(gifts[0]),[link,setLink]=useState(""),[rows,setRows]=useState<LinkRow[]>([]),[msg,setMsg]=useState(""),[newPin,setNewPin]=useState("");
 async function call(action:string,extra={}){const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,pin,...extra})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Error");return d}
 async function login(){try{await call("login");setOk(true);setMsg("");load()}catch(e){setMsg(e instanceof Error?e.message:"Error")}}
 async function load(){try{const d=await call("list");setRows(d.links)}catch{}}
 async function create(){try{const d=await call("create",{name,mobile,prize});const url=`${location.origin}/spin?token=${d.token}`;setLink(url);setMsg("One-time Spin link तैयार है");load()}catch(e){setMsg(e instanceof Error?e.message:"Error")}}
 async function change(){try{await call("changePin",{newPin});setPin(newPin);setNewPin("");setMsg("Admin PIN बदल गया") }catch(e){setMsg(e instanceof Error?e.message:"Error")}}
 function share(){const text=`नमस्ते ${name} जी 🙏\nShiv Ganga Mobile की तरफ से आपका Gift तैयार है।\nअपना तय Gift जानने के लिए One-Time Spin करें:\n${link}`;open(`https://wa.me/91${mobile}?text=${encodeURIComponent(text)}`,"_blank")}
 if(!ok)return <main className="admin-shell"><section className="login-card"><div className="admin-logo">SGM</div><small>SECURE ADMIN</small><h1>Gift Link Generator</h1><p>अपना 4-digit Admin PIN डालें</p><input inputMode="numeric" maxLength={4} type="password" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} placeholder="••••"/><button onClick={login}>LOGIN →</button>{msg&&<b className="error">{msg}</b>}<em>पहली बार Temporary PIN: 2580</em></section></main>;
 return <main className="admin-shell"><header className="admin-head"><div><small>SHIV GANGA MOBILE</small><h1>One-Time Gift Spin</h1></div><button onClick={()=>setOk(false)}>🔒 Logout</button></header><div className="admin-grid"><section className="panel create-panel"><span className="step">NEW CUSTOMER LINK</span><h2>Gift चुनें और Link बनाएँ</h2><label>Customer Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="ग्राहक का नाम"/></label><label>WhatsApp Mobile<input inputMode="numeric" maxLength={10} value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,""))} placeholder="10-digit mobile"/></label><label>Customer को कौन-सा Gift देना है?<select value={prize} onChange={e=>setPrize(e.target.value)}>{gifts.map(g=><option key={g}>{g}</option>)}</select></label><button className="gold-btn" onClick={create}>GENERATE ONE-TIME LINK</button>{msg&&<p className="status-msg">{msg}</p>}{link&&<div className="link-box"><small>READY TO SEND</small><p>{link}</p><div><button onClick={()=>navigator.clipboard.writeText(link)}>📋 Copy</button><button className="wa" onClick={share}>WhatsApp भेजें</button></div></div>}</section><section className="panel side-panel"><span className="step">SECURITY</span><h2>Admin PIN बदलें</h2><div className="pin-row"><input inputMode="numeric" maxLength={4} value={newPin} onChange={e=>setNewPin(e.target.value.replace(/\D/g,""))} placeholder="New 4-digit PIN"/><button onClick={change}>CHANGE</button></div><div className="info"><b>✓ Link Spin होने तक valid</b><b>✓ Spin के बाद permanently expired</b><b>✓ Gift result database में save</b></div></section></div><section className="panel records"><div className="record-title"><div><span className="step">RECENT LINKS</span><h2>Customer Spin History</h2></div><button onClick={load}>↻ Refresh</button></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Mobile</th><th>Gift</th><th>Status</th><th>Date</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.customerName}</td><td>{r.mobile}</td><td>{r.prize}</td><td><span className={r.status}>{r.status.toUpperCase()}</span></td><td>{new Date(r.createdAt+"Z").toLocaleString("en-IN")}</td></tr>)}{!rows.length&&<tr><td colSpan={5}>अभी कोई link नहीं बना है</td></tr>}</tbody></table></div></section></main>}
